export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const SAVE_FUEL_SAVINGS_STARTED = 'SAVE_FUEL_SAVINGS_STARTED';
export const SAVE_FUEL_SAVINGS_COMPLETED = 'SAVE_FUEL_SAVINGS_COMPLETE';
export const SAVE_FUEL_SAVINGS_ERROR = 'SAVE_FUEL_SAVINGS_ERROR';

export const CALCULATE_FUEL_SAVINGS_STARTED = 'CALCULATE_FUEL_SAVINGS_STARTED';
export const CALCULATE_FUEL_SAVINGS_COMPLETED = 'CALCULATE_FUEL_SAVINGS_COMPLETE';
export const CALCULATE_FUEL_SAVINGS_ERROR = 'CALCULATE_FUEL_SAVINGS_ERROR';
